# Generated by Django 2.0.4 on 2018-07-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180630_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='img',
            field=models.ImageField(default='', upload_to='teacher/%Y/%m', verbose_name='教师封面'),
        ),
    ]
