# Generated by Django 2.0.4 on 2018-07-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeroTeacher',
            fields=[
            ],
            options={
                'verbose_name': '没有被点击过的老师',
                'verbose_name_plural': '没有被点击过的老师',
                'proxy': True,
                'indexes': [],
            },
            bases=('organization.teacher',),
        ),
    ]
