# Generated by Django 2.0.4 on 2018-06-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180619_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='生日'),
        ),
    ]
