# Generated by Django 2.0.4 on 2018-08-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180807_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifycodede',
            old_name='identifying',
            new_name='code',
        ),
    ]
