# Generated by Django 2.0.4 on 2018-07-26 03:59

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='轮播图')),
                ('index', models.IntegerField(default=0, verbose_name='轮播顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图片',
                'verbose_name_plural': '轮播图片',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='品牌名', max_length=50, verbose_name='商品名')),
                ('goods_sn', models.CharField(default='', help_text='商品货号', max_length=50, verbose_name='商品货号')),
                ('click_nums', models.CharField(default='', help_text='点击数', max_length=50, verbose_name='点击数')),
                ('sold_nums', models.CharField(default='', help_text='售卖数', max_length=50, verbose_name='售卖数')),
                ('goods_nums', models.CharField(default='', help_text='库存数', max_length=50, verbose_name='库存数')),
                ('market_price', models.FloatField(default=0.0, help_text='市场价格', verbose_name='市场价格')),
                ('shop_price', models.FloatField(default=0.0, help_text='售卖价格', verbose_name='售卖价格')),
                ('goods_brief', models.CharField(default='', help_text='商品简述', max_length=500, verbose_name='商品简述')),
                ('goods_desc', DjangoUeditor.models.UEditorField(default='', verbose_name='商品描述内容')),
                ('ship_free', models.BooleanField(default=False, help_text='是否免运费', verbose_name='是否免运费')),
                ('goods_front_img', models.ImageField(blank=True, help_text='商品首页图', null=True, upload_to='goods/images/', verbose_name='商品首页图')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否为新品')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否为热销商品')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=50, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别编号', max_length=50, verbose_name='类别编号')),
                ('desc', models.TextField(help_text='类别描述', verbose_name='类别描述')),
                ('category_type', models.CharField(choices=[(1, '一级类别'), (2, '二级类别'), (3, '三级类别')], help_text='类目级别', max_length=10, verbose_name='类目级别')),
                ('is_tab', models.BooleanField(default=False, help_text='是否导航', verbose_name='是否导航')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.GoodsCategory', verbose_name='父类目录级')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='品牌名', max_length=50, verbose_name='品牌名')),
                ('desc', models.TextField(default='', help_text='品牌描述', max_length=500, verbose_name='品牌描述')),
                ('image', models.ImageField(upload_to='brands/', verbose_name='图片上传')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(help_text='商品类目', on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类目')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='brand/images/', verbose_name='商品图片')),
                ('image_url', models.CharField(max_length=100, verbose_name='图片url')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(help_text='商品类目', on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类目'),
        ),
        migrations.AddField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品'),
        ),
    ]
