# Generated by Django 2.0.4 on 2018-07-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180726_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='click_num',
            field=models.IntegerField(default=0, help_text='点击数', verbose_name='点击数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_num',
            field=models.IntegerField(default=0, help_text='库存数', verbose_name='库存数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sold_num',
            field=models.IntegerField(default=0, help_text='售卖数', verbose_name='售卖数'),
        ),
    ]
