# Generated by Django 2.0.4 on 2018-08-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20180728_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(upload_to='brands/images/', verbose_name='商品图片'),
        ),
    ]
