# Generated by Django 2.2 on 2019-05-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App01Apartment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dormitoryno', models.CharField(blank=True, max_length=255, null=True)),
                ('han', models.CharField(blank=True, max_length=255, null=True)),
                ('others', models.CharField(blank=True, db_column='others', max_length=255, null=True)),
            ],
            options={
                'db_table': 'app01apartment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='App01Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_name', models.CharField(db_column='Apartment_name', max_length=32)),
            ],
            options={
                'db_table': 'app01area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='App01Student',
            fields=[
                ('student_no', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('classes', models.CharField(blank=True, max_length=255, null=True)),
                ('male', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('nation', models.CharField(blank=True, db_column='Nation', max_length=255, null=True)),
            ],
            options={
                'db_table': 'app01student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='App01Teacher',
            fields=[
                ('teacher_no', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(blank=True, max_length=255, null=True)),
                ('male', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'app01teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'manager',
                'managed': False,
            },
        ),
    ]
