# Generated by Django 2.0.4 on 2018-07-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '視屏', 'verbose_name_plural': '視屏'},
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default=1, max_length=100, verbose_name='访问链接'),
            preserve_default=False,
        ),
    ]
