# Generated by Django 2.0.4 on 2018-07-12 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_img'),
        ('courses', '0004_auto_20180712_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='讲师'),
            preserve_default=False,
        ),
    ]
